# ----------------------------------------------------------------------------
# Copyright © 2023, Tiarnach Ó Riada
#
# Licensed under the terms of the Apache Software License 2.0
# ----------------------------------------------------------------------------

codecov:
  notify:
    require_ci_to_pass: no

codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "0...100"

  status:
    project:
      default:
        threshold: 5%
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: false
