# ----------------------------------------------------------------------------
# Copyright © 2023, Tiarnach Ó Riada
#
# Licensed under the terms of the Apache Software License 2.0
# ----------------------------------------------------------------------------

commit_message: '[ci skip] New %language% translation from Crowdin'
append_commit_message: false
files:
  - source: /spyder_pygmid/spyder/locale/spyder_pygmid.pot
    translation: /spyder_pygmid/spyder_pygmid/locale/%two_letters_code%/LC_MESSAGES/%file_name%.po
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        zh-CN: zh_CN
